# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image to build the project
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Build the project
RUN npm run build

# Use a smaller Node.js image for the final release
FROM node:20-alpine AS release

# Set working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/dist /app/dist

# Copy node_modules to the release image
COPY --from=builder /app/node_modules /app/node_modules

# Copy package.json to the release image
COPY --from=builder /app/package.json /app/package.json

# Copy .env.example and rename it to .env for environment variables
COPY .env.example .env

# Set environment variables (these should be provided at runtime in practice)
ENV X_API_KEY=your_api_key
ENV X_API_SECRET=your_api_secret
ENV X_ACCESS_TOKEN=your_access_token
ENV X_ACCESS_TOKEN_SECRET=your_access_token_secret

# Expose the port the app runs on
EXPOSE 3000

# Start the server
CMD ["node", "dist/index.js"]